/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemadeventaseinventario.GUI.Modulos;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frank
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        mostrartablas();
    }

    public void InitStyles() {

    }

    private void mostrartablas() {

        DefaultTableModel tab1 = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };

        DefaultTableModel tab2 = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };

        String titulos[] = {"Codigo", "Producto", "Stock actual"};
        tab1.setColumnIdentifiers(titulos);
        tb1.setModel(tab1);
        tb1.getTableHeader().setReorderingAllowed(false);
        String titulos2[] = {"Codigo", "Producto", "Cantidad Vendida"};
        tab2.setColumnIdentifiers(titulos2);
        tb2.setModel(tab2);
        tb2.getTableHeader().setReorderingAllowed(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InicioPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        btnProdMasVend = new javax.swing.JButton();
        btnProdBajS = new javax.swing.JButton();

        InicioPanel.setBackground(new java.awt.Color(255, 255, 255));
        InicioPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        InicioPanel.setPreferredSize(new java.awt.Dimension(830, 423));

        jLabel1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 37, 41));
        jLabel1.setText("User");

        jLabel3.setFont(new java.awt.Font("Roboto ExtraBold", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 37, 41));
        jLabel3.setText("Welcome:");

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb2);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tb1);

        btnProdMasVend.setBackground(new java.awt.Color(255, 255, 255));
        btnProdMasVend.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btnProdMasVend.setForeground(new java.awt.Color(153, 255, 153));
        btnProdMasVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/dinero.png"))); // NOI18N
        btnProdMasVend.setText("Productos más vendidos");
        btnProdMasVend.setBorder(null);
        btnProdMasVend.setIconTextGap(15);
        btnProdMasVend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdMasVendMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdMasVendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdMasVendMouseExited(evt);
            }
        });
        btnProdMasVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdMasVendActionPerformed(evt);
            }
        });

        btnProdBajS.setBackground(new java.awt.Color(255, 255, 255));
        btnProdBajS.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        btnProdBajS.setForeground(new java.awt.Color(255, 102, 102));
        btnProdBajS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/advertencia (1).png"))); // NOI18N
        btnProdBajS.setText("Productos con bajo stock !!");
        btnProdBajS.setBorder(null);
        btnProdBajS.setIconTextGap(15);
        btnProdBajS.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnProdBajS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdBajSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdBajSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdBajSMouseExited(evt);
            }
        });
        btnProdBajS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdBajSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioPanelLayout.createSequentialGroup()
                        .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InicioPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnProdBajS, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                .addGap(28, 28, 28)
                                .addComponent(btnProdMasVend, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                            .addGroup(InicioPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(InicioPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdBajS)
                    .addComponent(btnProdMasVend, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdMasVendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdMasVendMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdMasVendMouseClicked

    private void btnProdMasVendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdMasVendMouseEntered
    }//GEN-LAST:event_btnProdMasVendMouseEntered

    private void btnProdMasVendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdMasVendMouseExited
    }//GEN-LAST:event_btnProdMasVendMouseExited

    private void btnProdMasVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdMasVendActionPerformed


    }//GEN-LAST:event_btnProdMasVendActionPerformed

    private void btnProdBajSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdBajSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdBajSMouseClicked

    private void btnProdBajSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdBajSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdBajSMouseEntered

    private void btnProdBajSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdBajSMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdBajSMouseExited

    private void btnProdBajSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdBajSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdBajSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JButton btnProdBajS;
    private javax.swing.JButton btnProdMasVend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    // End of variables declaration//GEN-END:variables
}
