/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeventaseinventario.GUI.Login;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import com.mycompany.sistemadeventaseinventario.GUI.Principal.Principal;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Frank
 */
public class Login extends javax.swing.JFrame {

    //ejemplo de pull en github
    int xMouse, yMouse;

    public Login() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackGround = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelXClose = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelminimize = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        paswordUser = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        panelIniciarsession = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        restPasword = new javax.swing.JLabel();
        HeaderExit = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setPreferredSize(new java.awt.Dimension(800, 500));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(11, 33, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/KENKER-LOGO (1).png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 150));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 127, 27));
        jLabel1.setText("FERRETERIA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, 40));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 243, 255));
        jLabel4.setText("EL YUNQUE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 250, 70));

        jLabel2.setBackground(new java.awt.Color(20, 63, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/fondoLogoFF.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 290, 205));

        panelXClose.setBackground(new java.awt.Color(11, 33, 56));

        jLabel11.setBackground(new java.awt.Color(106, 140, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelXCloseLayout = new javax.swing.GroupLayout(panelXClose);
        panelXClose.setLayout(panelXCloseLayout);
        panelXCloseLayout.setHorizontalGroup(
            panelXCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        panelXCloseLayout.setVerticalGroup(
            panelXCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelXCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelXClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 0, 60, -1));

        panelminimize.setBackground(new java.awt.Color(11, 33, 56));

        minimize.setBackground(new java.awt.Color(39, 53, 255));
        minimize.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        minimize.setForeground(new java.awt.Color(0, 0, 0));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelminimizeLayout = new javax.swing.GroupLayout(panelminimize);
        panelminimize.setLayout(panelminimizeLayout);
        panelminimizeLayout.setHorizontalGroup(
            panelminimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelminimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelminimizeLayout.setVerticalGroup(
            panelminimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelminimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 0, 60, 40));

        BackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 540));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources_img/Logo-min (1) (1).png"))); // NOI18N
        BackGround.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 70));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 127, 27));
        jLabel5.setText("EL YUNQUE");
        BackGround.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, 30));

        jLabel7.setBackground(new java.awt.Color(64, 64, 64));
        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("INICIAR SESIÒN");
        BackGround.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, 50));

        jLabel8.setBackground(new java.awt.Color(64, 64, 64));
        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CONTRASEÑA");
        BackGround.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(153, 153, 153));
        txtUser.setText("Ingrese su nombre de usuario");
        txtUser.setBorder(null);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserMousePressed(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        BackGround.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 390, 30));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 390, 10));

        jLabel9.setBackground(new java.awt.Color(64, 64, 64));
        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("USUARIO");
        BackGround.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, 30));

        paswordUser.setBackground(new java.awt.Color(255, 255, 255));
        paswordUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        paswordUser.setForeground(new java.awt.Color(153, 153, 153));
        paswordUser.setText("********");
        paswordUser.setBorder(null);
        paswordUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paswordUserMousePressed(evt);
            }
        });
        paswordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paswordUserActionPerformed(evt);
            }
        });
        BackGround.add(paswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 390, 30));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        BackGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 390, 10));

        panelIniciarsession.setBackground(new java.awt.Color(32, 138, 215));
        panelIniciarsession.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelIniciarsession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelIniciarsessionMousePressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(11, 33, 56));
        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(235, 243, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("iniciar sesión");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIniciarsessionLayout = new javax.swing.GroupLayout(panelIniciarsession);
        panelIniciarsession.setLayout(panelIniciarsessionLayout);
        panelIniciarsessionLayout.setHorizontalGroup(
            panelIniciarsessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        panelIniciarsessionLayout.setVerticalGroup(
            panelIniciarsessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarsessionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BackGround.add(panelIniciarsession, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 390, 40));

        restPasword.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        restPasword.setForeground(new java.awt.Color(18, 109, 183));
        restPasword.setText("Restablecer contaseña");
        restPasword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restPasword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restPaswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restPaswordMouseExited(evt);
            }
        });
        BackGround.add(restPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        HeaderExit.setBackground(new java.awt.Color(255, 255, 255));
        HeaderExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderExitMouseDragged(evt);
            }
        });
        HeaderExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderExitMousePressed(evt);
            }
        });
        HeaderExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BackGround.add(HeaderExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        panelIniciarsession.setBackground(new Color(16, 86, 148));


    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited

        panelIniciarsession.setBackground(new Color(32, 138, 215));


    }//GEN-LAST:event_jLabel10MouseExited

    private void restPaswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restPaswordMouseEntered

        restPasword.setForeground(new Color(16, 86, 148));


    }//GEN-LAST:event_restPaswordMouseEntered

    private void restPaswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restPaswordMouseExited
        restPasword.setForeground(new Color(106, 140, 255));

     }//GEN-LAST:event_restPaswordMouseExited

    private void panelIniciarsessionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIniciarsessionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelIniciarsessionMousePressed

    private void HeaderExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderExitMousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_HeaderExitMousePressed

    private void HeaderExitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderExitMouseDragged

        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        this.setLocation(X - xMouse, Y - yMouse);
    }//GEN-LAST:event_HeaderExitMouseDragged

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        jLabel11.setForeground(Color.WHITE);
        panelXClose.setBackground(Color.red);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jLabel11.setForeground(Color.BLACK);
        panelXClose.setBackground(new Color(11, 33, 56));

    }//GEN-LAST:event_jLabel11MouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(JFrame.ICONIFIED);
        panelminimize.setBackground(new Color(39, 53, 255));
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        panelminimize.setBackground(new Color(197, 200, 206));

    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited

        panelminimize.setBackground(new Color(11, 33, 56));


    }//GEN-LAST:event_minimizeMouseExited

    private void paswordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paswordUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paswordUserActionPerformed

    private void txtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMousePressed
       
        
        if (txtUser.getText().equals("Ingrese su nombre de usuario")) {
            txtUser.setText("");
            txtUser.setForeground(Color.BLACK);
        }
        if (String.valueOf(paswordUser.getPassword()).isEmpty()) {
            paswordUser.setText("********");
            paswordUser.setForeground(new Color(159, 159, 159));
        }

    }//GEN-LAST:event_txtUserMousePressed

    private void paswordUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paswordUserMousePressed

        if (String.valueOf(paswordUser.getPassword()).equals("********")) {
            paswordUser.setText("");
            paswordUser.setForeground(Color.BLACK);
        }
        if (txtUser.getText().isEmpty()) {
            txtUser.setText("Ingrese su nombre de usuario");
            txtUser.setForeground(new Color(159, 159, 159));
        }

     }//GEN-LAST:event_paswordUserMousePressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        FlatMTMaterialLighterIJTheme.setup();

        SwingUtilities.invokeLater(() -> {
            new Principal().setVisible(true);
        });
        this.dispose();


    }//GEN-LAST:event_jLabel10MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel HeaderExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel panelIniciarsession;
    private javax.swing.JPanel panelXClose;
    private javax.swing.JPanel panelminimize;
    private javax.swing.JPasswordField paswordUser;
    private javax.swing.JLabel restPasword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
